version: "3.9"

services:
  nginx:
    build: ./conf/nginx
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/var/www/html/static
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - auth

  auth:
    build: .
    command: gunicorn -c conf/gunicorn.py
    env_file:
      - conf/env/.prod-env
    volumes:
#      - /service:/code
#      - /conf/gunicron:/code/conf
      - static_volume:/code/staticfiles
    ports:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:14.0
    ports:
      - 5432
    env_file:
      - conf/env/.prod-env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - 6379

volumes:
  postgres_data:
  static_volume:

