version: "3.9"

services:

#  auth:
#    build: .
#    command: gunicorn -c conf/gunicorn.py
#    environment:
#      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
#      - POSTGRES_NAME=${POSTGRES_NAME}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_HOST=db
#      - POSTGRES_PORT=5431
#    volumes:
#      - static_volume:/code/staticfiles
#    ports:
#      - 8000
#    depends_on:
#      - db

  db:
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - 6379:6379

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./conf/nginx:/etc/nginx/conf.d
#    ports:
#      - 80:80

volumes:
  nginx_volume:
  postgres_data:

